apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-api
  template:
    metadata:
      labels:
        app: memory-api
    spec:
      containers:
      - name: memory-api
        image: tylerpitcher/pyapi:1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: memory-api-service
spec:
  selector:
    app: memory-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
